# Project Configuration
project:
  name: "Cybersecurity Chatbot"
  version: "1.0.0"
  author: "RudraSuthar09"
  created_at: "2025-03-31 07:22:04"

# Data Configuration
data:
  nslkdd:
    train_path: "datasets/intrusion_detection/nslkdd/processed/KDDTrain+.csv"
    test_path: "datasets/intrusion_detection/nslkdd/processed/KDDTest+.csv"
    features: 42
    classes: 24

# Model Configuration
model:
  network_analyzer:
    input_size: 42
    hidden_size: 512
    num_layers: 6
    dropout: 0.3
    batch_size: 64
    learning_rate: 0.0003
    epochs: 50

  anomaly_detector:
    input_size: 122
    hidden_sizes: [64, 32]
    latent_size: 16
    learning_rate: 0.001
    epochs: 50
    batch_size: 64

# Training Configuration
training:
  seed: 42
  validation_split: 0.2
  early_stopping_patience: 15
  device: "cpu"
  class_weights: true
